# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 29a06ed6162804c2d7e96e3cdd15432a90b5782dca13a27b2beb560b6c12b2b094c718e7afd75b15bb71736682c2dca892a025bf036ba8140e85c2ac407f5b15

test:
  secret_key_base: ced2c8921ba59a5bb92161cc1b69de8ca0a8796ff3ae62b4cd8bf4a44be3572fb5a6b4d21727dc789d51bd053e99601e94e62466129b235d2d05f41aa3fedfc0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
